version: $(APPVEYOR_BUILD_NUMBER)
platform: x64
matrix:
  fast_finish: true

environment:
  PYPI_PASSWD:
    secure: u+K6dKi7+CXXVFEUG4V7zUyV3w7Ntg0Ork/RGVV0eSQ=
  matrix:
    - PYTHON: "C:\\Python35-x64"
    # - PYTHON: "C:\\Python35"
    # - PYTHON: "C:\\Python27"
    # - PYTHON: "C:\\Python27-x64"

install:
  - "build.cmd %PYTHON%\\python.exe -m pip install -U pip"
  - "build.cmd %PYTHON%\\python.exe -m pip install wheel"
#  - "build.cmd %PYTHON%\\python.exe -m pip install twine"
  - "build.cmd %PYTHON%\\python.exe -m pip install -r requirements-test.txt"
  - "build.cmd %PYTHON%\\python.exe -m pip install -e ."


build: false

test_script:
  - "build.cmd %PYTHON%\\python.exe -m pytest -vvv"
  - "build.cmd %PYTHON%\\python.exe -m pip install -r requirements-pyinstaller.txt -U urllib3[secure]"
  - "build.cmd %PYTHON%\\python.exe -m pip uninstall -y datarobot_batch_scoring"
  - "build.cmd %PYTHON%\\Scripts\\pyinstaller.exe -y --distpath=dist/ --onefile -n batch_scoring batch_scoring.py"
  - "build.cmd %PYTHON%\\Scripts\\pyinstaller.exe -y --distpath=dist/ --onefile -n batch_scoring_sse batch_scoring_sse.py"
  - "dist\\batch_scoring.exe --host=https://foo.bar.com --user=fooy@example.com --api_token=00000000000000000000000000000032 --datarobot_key=000000000000000000000000000000000036 000000000000000000000024 000000000000000000000024 tests/fixtures/criteo_top30_1m.csv.gz --dry_run --compress  -y"
  - "dist\\batch_scoring_sse.exe --host=https://foo.bar.com  000000000000000000000024 tests/fixtures/criteo_top30_1m.csv.gz --dry_run --compress  -y"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
  - "build.cmd mkdir build\\PR\\datarobot_batch_scoring_%APPVEYOR_REPO_COMMIT%_executables.Windows.x86_64"
  - "build.cmd mkdir build\\TAG\\datarobot_batch_scoring_%APPVEYOR_REPO_TAG_NAME%_executables.Windows.x86_64"
  - "build.cmd COPY dist\\batch_scoring.exe +dist\\batch_scoring_sse.exe +BATCH_SCORING_EXECUTABLE_README.txt build\\PR\\datarobot_batch_scoring_%APPVEYOR_REPO_COMMIT%_executables.Windows.x86_64"
  - "build.cmd COPY dist\\batch_scoring.exe +dist\\batch_scoring_sse.exe +BATCH_SCORING_EXECUTABLE_README.txt build\\TAG\\datarobot_batch_scoring_%APPVEYOR_REPO_TAG_NAME%_executables.Windows.x86_64"
  - "build.cmd 7z a build\\PR\\datarobot_batch_scoring_%APPVEYOR_REPO_COMMIT%_executables.Windows.x86_64.zip build\\PR\\datarobot_batch_scoring_%APPVEYOR_REPO_COMMIT%_executables.Windows.x86_64"
  - "build.cmd 7z a build\\TAG\\datarobot_batch_scoring_%APPVEYOR_REPO_TAG_NAME%_executables.Windows.x86_64.zip build\\TAG\\datarobot_batch_scoring_%APPVEYOR_REPO_TAG_NAME%_executables.Windows.x86_64"

artifacts:
  - path: dist\*

deploy:
  # This only pushes when a tag is pushed. This is the release build
  - provider: S3
    access_key_id: AKIAJ2W2S2GOXXIHGF6Q
    secret_access_key:
      secure: JunkjvwVSicgKSfNZzSWTqMyc5qLV4tkLNv0M/MQDM8f9B+2kwNt+F3Usj4EAZL9
    bucket: batch-scoring-release-candidates
    region: us-east-1
    set_public: false
    folder: windows-tagged-build/
    artifact: build\\TAG\\*.zip
    on:
      appveyor_repo_tag: true
      PYTHON: "C:\\Python35-x64"
  # This pushes a windows build on each PR
  - provider: S3
    access_key_id: AKIAJ2W2S2GOXXIHGF6Q
    secret_access_key:
      secure: JunkjvwVSicgKSfNZzSWTqMyc5qLV4tkLNv0M/MQDM8f9B+2kwNt+F3Usj4EAZL9
    bucket: batch-scoring-release-candidates
    region: us-east-1
    set_public: false
    folder: windows-dev-builds-not-for-release/$(APPVEYOR_BUILD_NUMBER)
    artifact: build\\PR\\*.zip
    on:
      appveyor_repo_tag: false
      PYTHON: "C:\\Python35-x64"


#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
