version: "2"
services:
  python26:
     image: batch-scoring-2.6
     build:
        context: .
        dockerfile: Dockerfile-2.6
     volumes:
        - .:/opt/project
  python27:
     image: batch-scoring-2.7
     build:
        context: .
        dockerfile: Dockerfile-2.7
     volumes:
        - .:/opt/project
  python35:
     image: batch-scoring-3.5
     build:
        context: .
        dockerfile: Dockerfile-3.5
     volumes:
        - .:/opt/project
  python27-dbg:
     image: batch-scoring-2.7-dbg
     privileged: true
     build:
        context: .
        dockerfile: Dockerfile-2.7-dbg
     volumes:
        - .:/opt/project
